# Generated by Django 3.1.1 on 2020-09-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, verbose_name='Вопрос')),
                ('input', models.CharField(choices=[('ch', 'checkbox'), ('rd', 'radio')], default='ch', max_length=2, verbose_name='Тип поля')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование теста')),
                ('timedelta', models.IntegerField(default=0, verbose_name='Время выполнения теста')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name=' Автор')),
            ],
            options={
                'ordering': ['title', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=55, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=55, verbose_name='Email')),
                ('sessionid', models.CharField(db_index=True, max_length=200)),
                ('answer', models.CharField(max_length=100, verbose_name='Список номеров ответов пользователя')),
                ('true_answer', models.CharField(max_length=100, verbose_name='Список номеров правильных ответов')),
                ('result', models.BooleanField(default=False, verbose_name='Результат')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('qwestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qwestion.qwestion', verbose_name='Вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qwestion.survey', verbose_name='Наменование теста')),
            ],
            options={
                'ordering': ['sessionid', '-created'],
            },
        ),
        migrations.AddField(
            model_name='qwestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qwestion.survey', verbose_name='Наименование теста'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, verbose_name='Ответ')),
                ('truefild', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('qwestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qwestion.qwestion', verbose_name='Вопрос')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
