# Generated by Django 3.1.1 on 2020-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='qwestion',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='qwestion',
            name='title',
            field=models.CharField(max_length=755, verbose_name='Вопрос'),
        ),
    ]
